version: '3.3'
services:
  api:
    build: api
    environment:
      RESULTS_DATA_DIR: /data/results
    volumes:
      - ./data:/data

    # Expose port 5000 for connecting from outside of the Docker container
    ports:
      - target: 5000
        published: 5000
        protocol: tcp
#        mode: host

  scheduler:
    build: scheduler
    depends_on:
      - api
    environment:
      DATA_DIR: /data
    volumes:
      - ./data:/data

    ports:
      - target: 5001
        published: 5001
        protocol: tcp
#        mode: host
